"""Generate the SDF archives used by the public training entry point.

Training uses prepared canonical triangle meshes. Inference starts from masks
and does not use this script.
"""

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from pathlib import Path

import numpy as np
import trimesh

from mesh_to_sdf.mesh_to_sdf import sample_sdf_near_surface
from project_config import (
    MIN_FREE_SPACE_GB,
    PREPROCESS_WORKERS,
    PROCESS_ROOT,
    RANDOM_SEED,
    REPO_ROOT,
    SDF_SAMPLE_COUNT,
    SURFACE_SAMPLE_COUNT,
    SURFACES,
    TRAIN_DATA_ROOT,
    TRAIN_MESH_ROOT,
    TRANSFORM_ROOT,
)


SPLITS = ("train",)
TRAIN_CASE_IDS = None
TRAIN_PHASES = None
OVERWRITE = False
VALIDATE_ONLY = False

TRAIN_KEYS = {"pos", "neg", "t", "P", "Pi", "offset", "scale"}


def load_transform(path):
    blocks = {}
    current = None
    rows = []
    for raw_line in Path(path).read_text().splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.endswith(":"):
            if current is not None:
                blocks[current] = np.asarray(rows, dtype=np.float64)
            current = line[:-1]
            rows = []
        else:
            rows.append([float(value) for value in line.split()])
    if current is not None:
        blocks[current] = np.asarray(rows, dtype=np.float64)
    missing = {"P", "Pi", "offset", "scale"} - blocks.keys()
    if missing:
        raise ValueError(f"{path} is missing transform blocks: {sorted(missing)}")
    return {
        "P": blocks["P"],
        "Pi": blocks["Pi"],
        "offset": blocks["offset"].reshape(-1),
        "scale": blocks["scale"].reshape(-1),
    }


def discover_frames(source_root, surface, patients=None, phases=None):
    frames = []
    if patients is None:
        patients = tuple(path.name for path in source_root.iterdir() if path.is_dir())
    allowed_patients = set(str(value) for value in patients)
    for patient_dir in sorted(path for path in source_root.iterdir() if path.is_dir()):
        if patient_dir.name not in allowed_patients:
            continue
        suffix = f"-{surface}.obj"
        phase_files = sorted(
            (path for path in patient_dir.iterdir() if path.name.endswith(suffix)),
            key=lambda path: int(path.name[:-len(suffix)]),
        )
        for phase_index, mesh_path in enumerate(phase_files):
            phase_name = mesh_path.name[:-len(suffix)]
            if int(phase_name) != phase_index:
                raise ValueError(
                    f"Non-contiguous phases for {patient_dir.name}-{surface}: "
                    f"expected {phase_index:02d}, found {phase_name}"
                )
            if phases is None or phase_index in phases:
                frames.append((patient_dir.name, phase_index, len(phase_files), mesh_path))
    return frames


def validate_npz(path, split):
    if split != "train":
        return False, "only train NPZ archives are supported"
    expected = TRAIN_KEYS
    try:
        with np.load(path, allow_pickle=False) as archive:
            if set(archive.files) != expected:
                return False, f"keys={sorted(archive.files)}"
            point_keys = ("pos", "neg")
            for key in point_keys:
                values = archive[key]
                if values.ndim != 2 or values.shape[1] != 4 or values.shape[0] == 0:
                    return False, f"{key}.shape={values.shape}"
                if not np.isfinite(values).all():
                    return False, f"{key} contains non-finite values"
            if archive["P"].shape != (4, 4) or archive["Pi"].shape != (4, 4):
                return False, "P/Pi must be 4x4"
            for key in expected - set(point_keys):
                if not np.isfinite(archive[key]).all():
                    return False, f"{key} contains non-finite values"
    except Exception as error:
        return False, repr(error)
    return True, "ok"


def atomic_savez(path, **arrays):
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(prefix=path.stem + ".", suffix=".npz", dir=path.parent, delete=False)
    temporary = Path(handle.name)
    handle.close()
    try:
        np.savez_compressed(temporary, **arrays)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _stable_seed(path):
    digest = hashlib.sha256(f"{path.parent.name}/{path.name}".encode("utf8")).digest()
    return RANDOM_SEED + int.from_bytes(digest[:4], "little")


def process_frame(split, surface, patient, phase_index, frame_count, input_path):
    if split != "train":
        raise ValueError("Only the train split is generated by the public processor")
    output_path = PROCESS_ROOT / f"{patient}_{phase_index:02d}-{surface}.npz"
    if output_path.exists() and not OVERWRITE:
        valid, _ = validate_npz(output_path, split)
        if valid:
            return output_path, "skipped"
    if VALIDATE_ONLY:
        valid, reason = validate_npz(output_path, split)
        if not valid:
            raise ValueError(f"Invalid {output_path}: {reason}")
        return output_path, "validated"

    transform = load_transform(TRANSFORM_ROOT / f"{patient}.txt")
    time_value = np.float32(phase_index / max(frame_count - 1, 1))
    mesh = trimesh.load(input_path, process=False)
    if isinstance(mesh, trimesh.Scene):
        mesh = mesh.dump(concatenate=True)

    if split == "train":
        if not isinstance(mesh, trimesh.Trimesh):
            raise TypeError(f"Expected a triangular training OBJ mesh: {input_path}")
        if len(mesh.faces) == 0:
            raise ValueError(f"Training mesh has no faces: {input_path}")
        # The local sampler uses NumPy's global generator internally.
        np.random.seed(_stable_seed(input_path) % (2**32 - 1))
        points, sdf = sample_sdf_near_surface(
            mesh,
            number_of_points=SDF_SAMPLE_COUNT,
            sampling_type="sphere",
            surface_point_method="sample",
            sign_method="normal",
            scan_count=0,
            scan_resolution=0,
            sample_point_count=SURFACE_SAMPLE_COUNT,
            normal_sample_count=5,
            min_size=0,
            return_gradients=False,
            test_sampling=False,
        )
        positive = np.column_stack((points[sdf > 0], sdf[sdf > 0])).astype(np.float32)
        negative = np.column_stack((points[sdf < 0], sdf[sdf < 0])).astype(np.float32)
        arrays = {"pos": positive, "neg": negative, "t": time_value, **transform}
    atomic_savez(output_path, **arrays)
    valid, reason = validate_npz(output_path, split)
    if not valid:
        output_path.unlink(missing_ok=True)
        raise ValueError(f"Generated invalid archive {output_path}: {reason}")
    return output_path, "written"


def build_manifest(surface):
    manifest = {"train": {"training": {}}, "test": {}}
    for patient, phase_index, _, _ in discover_frames(
        TRAIN_MESH_ROOT, surface, TRAIN_CASE_IDS, TRAIN_PHASES
    ):
        sequence_name = f"{patient}-{surface}"
        sequence = manifest["train"]["training"].setdefault(
            sequence_name, {"instance_list": []}
        )
        output_path = PROCESS_ROOT / f"{patient}_{phase_index:02d}-{surface}.npz"
        try:
            manifest_path = output_path.resolve().relative_to(REPO_ROOT.resolve())
        except ValueError:
            manifest_path = output_path.resolve()
        sequence["instance_list"].append(manifest_path.as_posix())
    return manifest


def write_manifests(surfaces=SURFACES):
    TRAIN_DATA_ROOT.mkdir(parents=True, exist_ok=True)
    for surface in surfaces:
        destination = TRAIN_DATA_ROOT / f"data_load_{surface}.json"
        destination.write_text(json.dumps(build_manifest(surface), indent=2) + "\n")


def verify_generated_subset(surfaces=SURFACES):
    errors = []
    total = 0
    for surface in surfaces:
        manifest = build_manifest(surface)
        expected_paths = [
            REPO_ROOT / item
            for sequence in manifest["train"]["training"].values()
            for item in sequence["instance_list"]
        ]
        total += len(expected_paths)
        for path in expected_paths:
            valid, reason = validate_npz(path, "train")
            if not valid:
                errors.append(f"{path}: {reason}")
    if errors:
        raise RuntimeError("NPZ validation failed:\n" + "\n".join(errors[:50]))
    return total


def _build_parser():
    parser = argparse.ArgumentParser(
        description="Convert canonical training meshes into 4DMM SDF archives."
    )
    parser.add_argument(
        "--training-data-root", type=Path, default=TRAIN_DATA_ROOT,
        help="training data directory (default: training_data)",
    )
    parser.add_argument(
        "--case", dest="case_ids", action="append",
        help="process only this case; repeat for multiple cases",
    )
    parser.add_argument(
        "--phase", dest="phases", type=int, action="append",
        help="process only this zero-based phase; repeat for multiple phases",
    )
    parser.add_argument(
        "--surface", choices=SURFACES, action="append",
        help="process only this surface; repeat to select both",
    )
    parser.add_argument(
        "--sdf-samples", type=int, default=SDF_SAMPLE_COUNT,
        help="SDF samples generated per frame",
    )
    parser.add_argument(
        "--surface-samples", type=int, default=SURFACE_SAMPLE_COUNT,
        help="surface samples used by the SDF sampler",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--validate-only", action="store_true")
    return parser


def _apply_cli_args(args):
    global TRAIN_DATA_ROOT, TRAIN_MESH_ROOT, TRANSFORM_ROOT, PROCESS_ROOT
    global TRAIN_CASE_IDS, TRAIN_PHASES, OVERWRITE, VALIDATE_ONLY
    global SDF_SAMPLE_COUNT, SURFACE_SAMPLE_COUNT

    root = args.training_data_root
    if not root.is_absolute():
        root = REPO_ROOT / root
    TRAIN_DATA_ROOT = root.resolve()
    TRAIN_MESH_ROOT = TRAIN_DATA_ROOT / "obj_norm_uv"
    TRANSFORM_ROOT = TRAIN_DATA_ROOT / "P" / "P_lv"
    PROCESS_ROOT = TRAIN_DATA_ROOT / "processed"
    TRAIN_CASE_IDS = tuple(args.case_ids) if args.case_ids else None
    TRAIN_PHASES = tuple(args.phases) if args.phases else None
    OVERWRITE = args.overwrite
    VALIDATE_ONLY = args.validate_only
    if args.sdf_samples < 1 or args.surface_samples < 1:
        raise ValueError("sample counts must be positive")
    SDF_SAMPLE_COUNT = args.sdf_samples
    SURFACE_SAMPLE_COUNT = args.surface_samples
    return tuple(dict.fromkeys(args.surface or SURFACES))


def main(argv=None):
    args = _build_parser().parse_args(argv)
    surfaces = _apply_cli_args(args)
    if not TRAIN_MESH_ROOT.is_dir():
        raise FileNotFoundError(
            f"Training mesh directory does not exist: {TRAIN_MESH_ROOT}"
        )
    free_gb = shutil.disk_usage(REPO_ROOT).free / 1024**3
    if not VALIDATE_ONLY and free_gb < MIN_FREE_SPACE_GB:
        raise RuntimeError(f"Only {free_gb:.1f} GB free; at least {MIN_FREE_SPACE_GB} GB is required")
    print(f"Repository: {REPO_ROOT}")
    print(f"Free space: {free_gb:.1f} GB; workers: {PREPROCESS_WORKERS}")

    for split in SPLITS:
        source_root = TRAIN_MESH_ROOT
        patients = TRAIN_CASE_IDS
        phases = TRAIN_PHASES
        for surface in surfaces:
            frames = discover_frames(source_root, surface, patients, phases)
            print(f"{split}/{surface}: {len(frames)} frames")
            for index, frame in enumerate(frames, 1):
                output, status = process_frame(split, surface, *frame)
                if index == 1 or index % 25 == 0 or index == len(frames):
                    print(f"[{split}/{surface}] {index}/{len(frames)} {status}: {output.name}", flush=True)

    write_manifests(surfaces)
    total = verify_generated_subset(surfaces)
    print(f"Validation complete: {total} selected NPZ files")


if __name__ == "__main__":
    main()
